version: '3'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=productive
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    image: bazel/backend:docker
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/productive

    depends_on:
      - db
volumes:
  db: