server:
  port: 8080
spring:
  # Fixes warning related to OIV
  jpa:
    open-in-view: false

  # https://spring.io/blog/2018/11/08/spring-boot-in-a-container
  jmx:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: dev
    password: dev
    url: jdbc:postgresql://:5432/productive
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:14:///productive